env:
- GO111MODULE=on
before:
  hooks:
  - go mod download
builds:
- binary: pinkie
  env:
  - CGO_ENABLED=0
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  ignore:
  - goarch: 386
    goos: darwin
  main: ./cmd/pinkie/main.go
dockers:
- build_flag_templates:
  - '--pull'
  - '--label=org.opencontainers.image.authors=Haneru Developers'
  - '--label=org.opencontainers.image.created={{.Date}}'
  - '--label=org.opencontainers.image.description=Enjoyment to be watched by you.'
  - '--label=org.opencontainers.image.licenses=MIT'
  - '--label=org.opencontainers.image.revision={{.FullCommit}}'
  - '--label=org.opencontainers.image.source={{.GitURL}}'
  - '--label=org.opencontainers.image.title={{.ProjectName}}'
  - '--label=org.opencontainers.image.url=https://github.com/inabagumi/pinkie'
  - '--label=org.opencontainers.image.version={{.Version}}'
  dockerfile: Dockerfile
  image_templates:
  - "inabagumi/{{ .ProjectName }}:latest"
  - "ghcr.io/inabagumi/{{ .ProjectName }}:latest"
  - "docker.pkg.github.com/inabagumi/pinkie/{{ .ProjectName }}:latest"
  - "{{ if index .Env \"GOOGLE_REGION\" }}{{ .Env.GOOGLE_REGION }}-docker.{{ end }}pkg.dev/{{ .Env.GOOGLE_PROJECT }}/containers/{{ .ProjectName }}:latest"
  - "inabagumi/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - "ghcr.io/inabagumi/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - "docker.pkg.github.com/inabagumi/pinkie/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - "{{ if index .Env \"GOOGLE_REGION\" }}{{ .Env.GOOGLE_REGION }}-docker.{{ end }}pkg.dev/{{ .Env.GOOGLE_PROJECT }}/containers/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - "inabagumi/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
  - "ghcr.io/inabagumi/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
  - "docker.pkg.github.com/inabagumi/pinkie/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
  - "{{ if index .Env \"GOOGLE_REGION\" }}{{ .Env.GOOGLE_REGION }}-docker.{{ end }}pkg.dev/{{ .Env.GOOGLE_PROJECT }}/containers/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^build(?:\([^)]+\))?:'
    - '^chore(?:\([^)]+\))?:'
    - '^ci(?:\([^)]+\))?:'
    - '^docs(?:\([^)]+\))?:'
    - '^refactor(?:\([^)]+\))?:'
    - '^test(?:\([^)]+\))?:'
    - '^v\d+(?:\.\d+){0,2}$'
