env:
- GO111MODULE=on
before:
  hooks:
  - go mod download
builds:
- main: ./cmd/ytc/main.go
  binary: ytc
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  ignore:
  - goos: darwin
    goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
