name: Go

on:
  pull_request:
    branches:
    - master

  push:
    branches:
    - master
    tags:
    - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      env:
        GO111MODULE: on
      run: go mod download

    - name: Build
      env:
        GO111MODULE: on
      run: go build -o bin/pinkie ./cmd/pinkie/main.go

    - name: Test
      env:
        GO111MODULE: on
      run: go test ./...

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: curl -sL https://git.io/goreleaser | bash
