name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          release-type: go
          package-name: pinkie
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
        if: ${{ steps.release.outputs.release_created }}
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
        if: ${{ steps.release.outputs.release_created }}
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
        if: ${{ steps.release.outputs.release_created }}
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
        if: ${{ steps.release.outputs.release_created }}
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: 1.5.0
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

