name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          package-name: pinkie
          release-type: go
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - if: ${{ steps.release.outputs.release_created }}
        id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          token_format: access_token
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      - if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
      - if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        if: ${{ steps.release.outputs.release_created }}
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release
          version: 1.9.2
