name: Release

on:
  pull_request:
    branches:
    - '!*'

  push:
    branches:
    - '!*'
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}
    - uses: goreleaser/goreleaser-action@v2
      with:
        version: 1.5.0
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
